-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.basket_items
(
    basket_id uuid NOT NULL,
    item_id uuid NOT NULL,
    quantity smallint NOT NULL,
    CONSTRAINT basket_items_pkey PRIMARY KEY (basket_id, item_id)
);

CREATE TABLE IF NOT EXISTS public.baskets
(
    basket_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    active boolean NOT NULL,
    reserved_at timestamp without time zone,
    CONSTRAINT basket_pkey PRIMARY KEY (basket_id)
);

CREATE TABLE IF NOT EXISTS public.item_reviews
(
    review_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    item_id uuid NOT NULL,
    rating smallint NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT item_reviews_pkey PRIMARY KEY (review_id)
);

CREATE TABLE IF NOT EXISTS public.items
(
    item_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    store_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    nutrition json NOT NULL,
    price numeric(8, 2) NOT NULL,
    picture text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    quantity integer NOT NULL DEFAULT 0,
    CONSTRAINT items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_item_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    order_id uuid NOT NULL,
    item_id uuid NOT NULL,
    quantity integer NOT NULL,
    price numeric(8, 2) NOT NULL,
    total numeric(8, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    store_id uuid NOT NULL,
    subtotal numeric(8, 2) NOT NULL,
    delivery_fee numeric(8, 2) NOT NULL,
    total_price numeric(8, 2) NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    delivery_address text COLLATE pg_catalog."default" NOT NULL,
    delivery_postcode text COLLATE pg_catalog."default" NOT NULL,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    card_number bigint,
    name_on_card text COLLATE pg_catalog."default",
    expiry_date date,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.store_reviews
(
    review_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    store_id uuid NOT NULL,
    rating smallint NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT store_reviews_pkey PRIMARY KEY (review_id)
);

CREATE TABLE IF NOT EXISTS public.store_users
(
    store_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT store_users_pkey PRIMARY KEY (store_id, user_id),
    CONSTRAINT store_users_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.stores
(
    store_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name text COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    postcode text COLLATE pg_catalog."default" NOT NULL,
    opening_hours json NOT NULL,
    picture text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    description text COLLATE pg_catalog."default" NOT NULL,
    store_admin uuid,
    CONSTRAINT stores_pkey PRIMARY KEY (store_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    username text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    postcode text COLLATE pg_catalog."default",
    picture text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.basket_items
    ADD CONSTRAINT basket_items_basket_id_fkey FOREIGN KEY (basket_id)
    REFERENCES public.baskets (basket_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.basket_items
    ADD CONSTRAINT basket_items_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.baskets
    ADD CONSTRAINT basket_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.item_reviews
    ADD CONSTRAINT item_reviews_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.item_reviews
    ADD CONSTRAINT item_reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.items
    ADD CONSTRAINT items_store_id_fkey FOREIGN KEY (store_id)
    REFERENCES public.stores (store_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_store_id_fkey FOREIGN KEY (store_id)
    REFERENCES public.stores (store_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.store_reviews
    ADD CONSTRAINT store_reviews_store_id_fkey FOREIGN KEY (store_id)
    REFERENCES public.stores (store_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.store_reviews
    ADD CONSTRAINT store_reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.store_users
    ADD CONSTRAINT store_users_store_id_fkey FOREIGN KEY (store_id)
    REFERENCES public.stores (store_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.store_users
    ADD CONSTRAINT store_users_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS store_users_user_id_key
    ON public.store_users(user_id);


ALTER TABLE IF EXISTS public.stores
    ADD CONSTRAINT stores_store_admin_fkey FOREIGN KEY (store_admin)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;